#pragma once
// Simple OBJ writer used only by tests to produce visual debug output.

#include "gk/math/Vec3.h"
#include "gk/surface/SurfaceUtils.h"
#include <array>
#include <fstream>
#include <string>
#include <vector>

class ObjWriter {
public:
    ObjWriter() = default;

    void addVertex(gk::Vec3 v) { vertices_.push_back(v); }
    void addNormal(gk::Vec3 n) { normals_.push_back(n); }

    void addFace(int v1, int v2, int v3) {
        faces_.push_back({v1, -1, v2, -1, v3, -1});
    }

    void addFaceWithNormals(int v1, int n1, int v2, int n2, int v3, int n3) {
        faces_.push_back({v1, n1, v2, n2, v3, n3});
    }

    void addSurfaceMesh(const gk::SurfaceMesh& mesh) {
        int vOffset = (int)vertices_.size() + 1;
        int nOffset = (int)normals_.size() + 1;

        for (auto& v : mesh.vertices) vertices_.push_back(v);
        for (auto& n : mesh.normals)  normals_.push_back(n);

        for (auto& tri : mesh.triangles) {
            addFaceWithNormals(
                tri[0] + vOffset, tri[0] + nOffset,
                tri[1] + vOffset, tri[1] + nOffset,
                tri[2] + vOffset, tri[2] + nOffset);
        }
    }

    bool write(const std::string& path) {
        std::ofstream f(path);
        if (!f.is_open()) return false;
        f << "# OBJ file generated by ObjWriter\n";
        for (auto& v : vertices_)
            f << "v " << v.x << " " << v.y << " " << v.z << "\n";
        for (auto& n : normals_)
            f << "vn " << n.x << " " << n.y << " " << n.z << "\n";
        for (auto& face : faces_) {
            f << "f";
            for (int i = 0; i < 3; ++i) {
                int vi = face[i*2];
                int ni = face[i*2+1];
                if (ni < 0) f << " " << vi;
                else        f << " " << vi << "//" << ni;
            }
            f << "\n";
        }
        return true;
    }

private:
    std::vector<gk::Vec3> vertices_;
    std::vector<gk::Vec3> normals_;
    std::vector<std::array<int,6>> faces_;
};
