add_test([=[Sketch.TriangleTriangulate]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.TriangleTriangulate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.TriangleTriangulate]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sketch.RectangleTriangulate]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.RectangleTriangulate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.RectangleTriangulate]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sketch.HexagonTriangulate]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.HexagonTriangulate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.HexagonTriangulate]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sketch.HexWithHole]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.HexWithHole]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.HexWithHole]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sketch.RoundedRectangle]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.RoundedRectangle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.RoundedRectangle]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Sketch.DiscretizeLoopNonEmpty]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_sketch [==[--gtest_filter=Sketch.DiscretizeLoopNonEmpty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Sketch.DiscretizeLoopNonEmpty]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_sketch_TESTS Sketch.TriangleTriangulate Sketch.RectangleTriangulate Sketch.HexagonTriangulate Sketch.HexWithHole Sketch.RoundedRectangle Sketch.DiscretizeLoopNonEmpty)
