add_test([=[Builders5_1.BoxVolume]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.BoxVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.BoxVolume]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.BoxShifted]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.BoxShifted]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.BoxShifted]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.SphereVolume]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.SphereVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.SphereVolume]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.CylinderVolume]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.CylinderVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.CylinderVolume]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.ConeVolume]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.ConeVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.ConeVolume]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.BoxObjExport]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.BoxObjExport]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.BoxObjExport]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.SphereObjExport]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.SphereObjExport]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.SphereObjExport]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.CylinderObjExport]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.CylinderObjExport]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.CylinderObjExport]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Builders5_1.ConeObjExport]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_builders_5_1 [==[--gtest_filter=Builders5_1.ConeObjExport]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Builders5_1.ConeObjExport]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_builders_5_1_TESTS Builders5_1.BoxVolume Builders5_1.BoxShifted Builders5_1.SphereVolume Builders5_1.CylinderVolume Builders5_1.ConeVolume Builders5_1.BoxObjExport Builders5_1.SphereObjExport Builders5_1.CylinderObjExport Builders5_1.ConeObjExport)
