add_test([=[Interval.DefaultIsZeroPoint]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.DefaultIsZeroPoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.DefaultIsZeroPoint]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ValueConstruction]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ValueConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ValueConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.MakeSwaps]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.MakeSwaps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.MakeSwaps]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.PointFactory]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.PointFactory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.PointFactory]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Width]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Width]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Width]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Midpoint]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Midpoint]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Midpoint]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.IsEmpty]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.IsEmpty]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.IsEmpty]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Contains]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Contains]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Contains]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ContainsInterval]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ContainsInterval]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ContainsInterval]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Overlaps]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Overlaps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Overlaps]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Addition]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Addition]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Subtraction]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Subtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Subtraction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ScalarMultiplicationPositive]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ScalarMultiplicationPositive]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ScalarMultiplicationPositive]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ScalarMultiplicationNegative]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ScalarMultiplicationNegative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ScalarMultiplicationNegative]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Hull]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Hull]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Hull]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.Intersection]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.Intersection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.Intersection]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.EmptyIntersection]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.EmptyIntersection]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.EmptyIntersection]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ExactEquality]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ExactEquality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ExactEquality]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Interval.ToString]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_interval [==[--gtest_filter=Interval.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Interval.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_interval_TESTS Interval.DefaultIsZeroPoint Interval.ValueConstruction Interval.MakeSwaps Interval.PointFactory Interval.Width Interval.Midpoint Interval.IsEmpty Interval.Contains Interval.ContainsInterval Interval.Overlaps Interval.Addition Interval.Subtraction Interval.ScalarMultiplicationPositive Interval.ScalarMultiplicationNegative Interval.Hull Interval.Intersection Interval.EmptyIntersection Interval.FuzzyEquals Interval.ExactEquality Interval.ToString)
