add_test([=[BRepQueryTest.CubeSurfaceArea]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_query [==[--gtest_filter=BRepQueryTest.CubeSurfaceArea]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BRepQueryTest.CubeSurfaceArea]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BRepQueryTest.CubeVolume]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_query [==[--gtest_filter=BRepQueryTest.CubeVolume]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BRepQueryTest.CubeVolume]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BRepQueryTest.PointInsideCube]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_query [==[--gtest_filter=BRepQueryTest.PointInsideCube]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BRepQueryTest.PointInsideCube]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BRepQueryTest.PointOutsideCube]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_query [==[--gtest_filter=BRepQueryTest.PointOutsideCube]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BRepQueryTest.PointOutsideCube]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BRepQueryTest.TopologicalDistance]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_query [==[--gtest_filter=BRepQueryTest.TopologicalDistance]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BRepQueryTest.TopologicalDistance]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_brep_query_TESTS BRepQueryTest.CubeSurfaceArea BRepQueryTest.CubeVolume BRepQueryTest.PointInsideCube BRepQueryTest.PointOutsideCube BRepQueryTest.TopologicalDistance)
