add_test([=[CubeTopology.FaceCount]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_topology [==[--gtest_filter=CubeTopology.FaceCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CubeTopology.FaceCount]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CubeTopology.WiresClosed]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_topology [==[--gtest_filter=CubeTopology.WiresClosed]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CubeTopology.WiresClosed]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CubeTopology.EdgeCount]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_topology [==[--gtest_filter=CubeTopology.EdgeCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CubeTopology.EdgeCount]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CubeTopology.VertexCount]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_topology [==[--gtest_filter=CubeTopology.VertexCount]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CubeTopology.VertexCount]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CubeTopology.Traversal]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_brep_topology [==[--gtest_filter=CubeTopology.Traversal]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CubeTopology.Traversal]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_brep_topology_TESTS CubeTopology.FaceCount CubeTopology.WiresClosed CubeTopology.EdgeCount CubeTopology.VertexCount CubeTopology.Traversal)
