if(EXISTS "/home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_surface_obj[1]_tests.cmake")
  include("/home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_surface_obj[1]_tests.cmake")
else()
  add_test(test_surface_obj_NOT_BUILT test_surface_obj_NOT_BUILT)
endif()
