add_test([=[Mat4x4.DefaultIsZero]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.DefaultIsZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.DefaultIsZero]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.Identity]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.Identity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.Identity]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.MatVecMultiplication]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.MatVecMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.MatVecMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.MatMatMultiplication]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.MatMatMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.MatMatMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.Transpose]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.Transpose]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.Transpose]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.ScalarMultiplication]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.AdditionSubtraction]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.AdditionSubtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.AdditionSubtraction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat4x4.ToString]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_mat4x4 [==[--gtest_filter=Mat4x4.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat4x4.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_mat4x4_TESTS Mat4x4.DefaultIsZero Mat4x4.Identity Mat4x4.MatVecMultiplication Mat4x4.MatMatMultiplication Mat4x4.Transpose Mat4x4.ScalarMultiplication Mat4x4.AdditionSubtraction Mat4x4.FuzzyEquals Mat4x4.ToString)
