add_test([=[Extrusion.RectangleExtrude]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.RectangleExtrude]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.RectangleExtrude]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.TriangleExtrude]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.TriangleExtrude]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.TriangleExtrude]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.HexagonExtrude]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.HexagonExtrude]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.HexagonExtrude]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.RectangleRevolve]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.RectangleRevolve]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.RectangleRevolve]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.TriangleRevolve]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.TriangleRevolve]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.TriangleRevolve]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.TriangulateSketch]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.TriangulateSketch]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.TriangulateSketch]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Extrusion.ExtrudeVolumeApprox]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_extrusion [==[--gtest_filter=Extrusion.ExtrudeVolumeApprox]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Extrusion.ExtrudeVolumeApprox]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_extrusion_TESTS Extrusion.RectangleExtrude Extrusion.TriangleExtrude Extrusion.HexagonExtrude Extrusion.RectangleRevolve Extrusion.TriangleRevolve Extrusion.TriangulateSketch Extrusion.ExtrudeVolumeApprox)
