add_test([=[CurveIface.Line3EvaluateDomain]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.Line3EvaluateDomain]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.Line3EvaluateDomain]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CurveIface.TangentNormalized]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.TangentNormalized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.TangentNormalized]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CurveIface.ApproximateLength]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.ApproximateLength]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.ApproximateLength]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CurveIface.CurvatureCircle]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.CurvatureCircle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.CurvatureCircle]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CurveIface.Line3ZeroCurvature]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.Line3ZeroCurvature]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.Line3ZeroCurvature]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CurveIface.SVG_LineAndCircle]=]  /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests/test_curve_iface [==[--gtest_filter=CurveIface.SVG_LineAndCircle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CurveIface.SVG_LineAndCircle]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/_codeql_build_dir/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_curve_iface_TESTS CurveIface.Line3EvaluateDomain CurveIface.TangentNormalized CurveIface.ApproximateLength CurveIface.CurvatureCircle CurveIface.Line3ZeroCurvature CurveIface.SVG_LineAndCircle)
