if(EXISTS "/home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid[1]_tests.cmake")
  include("/home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid[1]_tests.cmake")
else()
  add_test(test_entityid_NOT_BUILT test_entityid_NOT_BUILT)
endif()
