add_test([=[Mat2x2.DefaultIsZero]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.DefaultIsZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.DefaultIsZero]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Identity]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Identity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Identity]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Addition]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Addition]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Subtraction]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Subtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Subtraction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.ScalarMultiplication]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.MatrixMultiplication]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.MatrixMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.MatrixMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.MatVecMultiplication]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.MatVecMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.MatVecMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Transpose]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Transpose]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Transpose]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Determinant]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Determinant]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Determinant]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.Inverse]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.Inverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.Inverse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.SingularInverse]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.SingularInverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.SingularInverse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat2x2.ToString]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_mat2x2 [==[--gtest_filter=Mat2x2.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat2x2.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_mat2x2_TESTS Mat2x2.DefaultIsZero Mat2x2.Identity Mat2x2.Addition Mat2x2.Subtraction Mat2x2.ScalarMultiplication Mat2x2.MatrixMultiplication Mat2x2.MatVecMultiplication Mat2x2.Transpose Mat2x2.Determinant Mat2x2.Inverse Mat2x2.SingularInverse Mat2x2.FuzzyEquals Mat2x2.ToString)
