add_test([=[Result.OkIsTrue]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.OkIsTrue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.OkIsTrue]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.OkValueIsCorrect]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.OkValueIsCorrect]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.OkValueIsCorrect]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.ErrIsFalse]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.ErrIsFalse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.ErrIsFalse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.ErrCodeAndMessage]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.ErrCodeAndMessage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.ErrCodeAndMessage]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.ValueOnErrorThrows]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.ValueOnErrorThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.ValueOnErrorThrows]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.ErrorOnOkThrows]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.ErrorOnOkThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.ErrorOnOkThrows]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.MapTransformsValue]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.MapTransformsValue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.MapTransformsValue]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.MapPropagatesError]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.MapPropagatesError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.MapPropagatesError]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.AndThenChains]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.AndThenChains]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.AndThenChains]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Result.AndThenShortCircuitsOnError]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Result.AndThenShortCircuitsOnError]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Result.AndThenShortCircuitsOnError]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResultVoid.OkIsTrue]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=ResultVoid.OkIsTrue]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResultVoid.OkIsTrue]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ResultVoid.ErrIsFalse]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=ResultVoid.ErrIsFalse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ResultVoid.ErrIsFalse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Error.ErrorCodeName]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Error.ErrorCodeName]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Error.ErrorCodeName]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Error.ToStringContainsCodeAndMessage]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Error.ToStringContainsCodeAndMessage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Error.ToStringContainsCodeAndMessage]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Error.ToStringContainsLocationInDebug]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_result [==[--gtest_filter=Error.ToStringContainsLocationInDebug]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Error.ToStringContainsLocationInDebug]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_result_TESTS Result.OkIsTrue Result.OkValueIsCorrect Result.ErrIsFalse Result.ErrCodeAndMessage Result.ValueOnErrorThrows Result.ErrorOnOkThrows Result.MapTransformsValue Result.MapPropagatesError Result.AndThenChains Result.AndThenShortCircuitsOnError ResultVoid.OkIsTrue ResultVoid.ErrIsFalse Error.ErrorCodeName Error.ToStringContainsCodeAndMessage Error.ToStringContainsLocationInDebug)
