add_test([=[SurfaceObjWriter.SphereObj]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_surface_obj [==[--gtest_filter=SurfaceObjWriter.SphereObj]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceObjWriter.SphereObj]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceObjWriter.CylinderObj]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_surface_obj [==[--gtest_filter=SurfaceObjWriter.CylinderObj]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceObjWriter.CylinderObj]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceObjWriter.TorusObj]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_surface_obj [==[--gtest_filter=SurfaceObjWriter.TorusObj]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceObjWriter.TorusObj]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceObjWriter.BSplineSurfaceObj]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_surface_obj [==[--gtest_filter=SurfaceObjWriter.BSplineSurfaceObj]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceObjWriter.BSplineSurfaceObj]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SurfaceObjWriter.TessellationVerticesOnSphere]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_surface_obj [==[--gtest_filter=SurfaceObjWriter.TessellationVerticesOnSphere]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SurfaceObjWriter.TessellationVerticesOnSphere]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_surface_obj_TESTS SurfaceObjWriter.SphereObj SurfaceObjWriter.CylinderObj SurfaceObjWriter.TorusObj SurfaceObjWriter.BSplineSurfaceObj SurfaceObjWriter.TessellationVerticesOnSphere)
