add_test([=[Vec2.DefaultConstruction]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.DefaultConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.DefaultConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.ValueConstruction]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.ValueConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.ValueConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.StaticFactories]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.StaticFactories]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.StaticFactories]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Addition]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Addition]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Subtraction]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Subtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Subtraction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.ScalarMultiplication]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.ScalarDivision]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.ScalarDivision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.ScalarDivision]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Negation]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Negation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Negation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.CompoundAssignment]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.CompoundAssignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.CompoundAssignment]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Dot]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Dot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Dot]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Cross]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Cross]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Cross]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Norm]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Norm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Norm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.Normalized]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.Normalized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.Normalized]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.NormalizedZeroVector]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.NormalizedZeroVector]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.NormalizedZeroVector]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.ExactEquality]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.ExactEquality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.ExactEquality]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec2.ToString]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_vec2 [==[--gtest_filter=Vec2.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec2.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_vec2_TESTS Vec2.DefaultConstruction Vec2.ValueConstruction Vec2.StaticFactories Vec2.Addition Vec2.Subtraction Vec2.ScalarMultiplication Vec2.ScalarDivision Vec2.Negation Vec2.CompoundAssignment Vec2.Dot Vec2.Cross Vec2.Norm Vec2.Normalized Vec2.NormalizedZeroVector Vec2.FuzzyEquals Vec2.ExactEquality Vec2.ToString)
