add_test([=[EntityId.DefaultIsInvalid]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.DefaultIsInvalid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.DefaultIsInvalid]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.InvalidSentinelIsInvalid]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.InvalidSentinelIsInvalid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.InvalidSentinelIsInvalid]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.GenerateReturnsValidId]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.GenerateReturnsValidId]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.GenerateReturnsValidId]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.GeneratedIdsAreUnique]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.GeneratedIdsAreUnique]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.GeneratedIdsAreUnique]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.Equality]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.Equality]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.Equality]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.LessThanOrdersById]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.LessThanOrdersById]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.LessThanOrdersById]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.InvalidLessThanValid]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.InvalidLessThanValid]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.InvalidLessThanValid]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[EntityId.ToString]=]  /home/runner/work/Gector2/Gector2/build_verify/tests/test_entityid [==[--gtest_filter=EntityId.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[EntityId.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_verify/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_entityid_TESTS EntityId.DefaultIsInvalid EntityId.InvalidSentinelIsInvalid EntityId.GenerateReturnsValidId EntityId.GeneratedIdsAreUnique EntityId.Equality EntityId.LessThanOrdersById EntityId.InvalidLessThanValid EntityId.ToString)
