add_test([=[Vec4.DefaultConstruction]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.DefaultConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.DefaultConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.ValueConstruction]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.ValueConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.ValueConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.StaticFactories]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.StaticFactories]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.StaticFactories]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.Arithmetic]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.Arithmetic]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.Arithmetic]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.Dot]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.Dot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.Dot]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.Norm]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.Norm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.Norm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.Normalized]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.Normalized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.Normalized]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec4.ToString]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec4 [==[--gtest_filter=Vec4.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec4.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_vec4_TESTS Vec4.DefaultConstruction Vec4.ValueConstruction Vec4.StaticFactories Vec4.Arithmetic Vec4.Dot Vec4.Norm Vec4.Normalized Vec4.FuzzyEquals Vec4.ToString)
