add_test([=[Vec3.DefaultConstruction]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.DefaultConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.DefaultConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.ValueConstruction]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.ValueConstruction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.ValueConstruction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.StaticFactories]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.StaticFactories]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.StaticFactories]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Addition]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Addition]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Addition]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Subtraction]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Subtraction]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Subtraction]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.ScalarMultiplication]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.ScalarMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.ScalarMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.ScalarDivision]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.ScalarDivision]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.ScalarDivision]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Negation]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Negation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Negation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.CompoundAssignment]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.CompoundAssignment]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.CompoundAssignment]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Dot]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Dot]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Dot]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Cross]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Cross]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Cross]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.CrossAnticommutative]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.CrossAnticommutative]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.CrossAnticommutative]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Norm]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Norm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Norm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.Normalized]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.Normalized]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.Normalized]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.NormalizedZero]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.NormalizedZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.NormalizedZero]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Vec3.ToString]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_vec3 [==[--gtest_filter=Vec3.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Vec3.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_vec3_TESTS Vec3.DefaultConstruction Vec3.ValueConstruction Vec3.StaticFactories Vec3.Addition Vec3.Subtraction Vec3.ScalarMultiplication Vec3.ScalarDivision Vec3.Negation Vec3.CompoundAssignment Vec3.Dot Vec3.Cross Vec3.CrossAnticommutative Vec3.Norm Vec3.Normalized Vec3.NormalizedZero Vec3.FuzzyEquals Vec3.ToString)
