if(EXISTS "/home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3[1]_tests.cmake")
  include("/home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3[1]_tests.cmake")
else()
  add_test(test_mat3x3_NOT_BUILT test_mat3x3_NOT_BUILT)
endif()
