add_test([=[Arena.AllocateReturnsNonNull]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.AllocateReturnsNonNull]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.AllocateReturnsNonNull]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.MultipleAllocationsDoNotOverlap]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.MultipleAllocationsDoNotOverlap]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.MultipleAllocationsDoNotOverlap]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.ConstructCallsConstructor]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.ConstructCallsConstructor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.ConstructCallsConstructor]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.AllocationsAreAligned]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.AllocationsAreAligned]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.AllocationsAreAligned]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.LargeAlignmentHonoured]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.LargeAlignmentHonoured]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.LargeAlignmentHonoured]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.ResetAllowsReuse]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.ResetAllowsReuse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.ResetAllowsReuse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.CapacityIsAtLeastBlockSize]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.CapacityIsAtLeastBlockSize]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.CapacityIsAtLeastBlockSize]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.NewBlockAllocatedWhenCurrentFull]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.NewBlockAllocatedWhenCurrentFull]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.NewBlockAllocatedWhenCurrentFull]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Arena.ZeroSizeAllocationSucceeds]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_arena [==[--gtest_filter=Arena.ZeroSizeAllocationSucceeds]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Arena.ZeroSizeAllocationSucceeds]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_arena_TESTS Arena.AllocateReturnsNonNull Arena.MultipleAllocationsDoNotOverlap Arena.ConstructCallsConstructor Arena.AllocationsAreAligned Arena.LargeAlignmentHonoured Arena.ResetAllowsReuse Arena.CapacityIsAtLeastBlockSize Arena.NewBlockAllocatedWhenCurrentFull Arena.ZeroSizeAllocationSucceeds)
