if(EXISTS "/home/runner/work/Gector2/Gector2/build_test/tests/test_mat2x2[1]_tests.cmake")
  include("/home/runner/work/Gector2/Gector2/build_test/tests/test_mat2x2[1]_tests.cmake")
else()
  add_test(test_mat2x2_NOT_BUILT test_mat2x2_NOT_BUILT)
endif()
