add_test([=[Logger.LevelNames]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.LevelNames]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.LevelNames]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.CustomSinkReceivesMessage]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.CustomSinkReceivesMessage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.CustomSinkReceivesMessage]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.SinkReceivesFileAndLine]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.SinkReceivesFileAndLine]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.SinkReceivesFileAndLine]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.MessagesFilteredBelowMinLevel]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.MessagesFilteredBelowMinLevel]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.MessagesFilteredBelowMinLevel]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.AllMacroLevels]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.AllMacroLevels]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.AllMacroLevels]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.ClearSinkIsHarmless]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.ClearSinkIsHarmless]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.ClearSinkIsHarmless]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Logger.MinLevelAccessor]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_log [==[--gtest_filter=Logger.MinLevelAccessor]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Logger.MinLevelAccessor]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_log_TESTS Logger.LevelNames Logger.CustomSinkReceivesMessage Logger.SinkReceivesFileAndLine Logger.MessagesFilteredBelowMinLevel Logger.AllMacroLevels Logger.ClearSinkIsHarmless Logger.MinLevelAccessor)
