add_test([=[Mat3x3.DefaultIsZero]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.DefaultIsZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.DefaultIsZero]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.Identity]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.Identity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.Identity]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.MatVecMultiplication]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.MatVecMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.MatVecMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.MatMatMultiplication]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.MatMatMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.MatMatMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.Transpose]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.Transpose]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.Transpose]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.Determinant]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.Determinant]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.Determinant]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.Inverse]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.Inverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.Inverse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.SingularInverse]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.SingularInverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.SingularInverse]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.RotationAxisAngle90]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.RotationAxisAngle90]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.RotationAxisAngle90]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.RotationPreservesNorm]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.RotationPreservesNorm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.RotationPreservesNorm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.FuzzyEquals]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.FuzzyEquals]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.FuzzyEquals]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Mat3x3.ToString]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_mat3x3 [==[--gtest_filter=Mat3x3.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Mat3x3.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_mat3x3_TESTS Mat3x3.DefaultIsZero Mat3x3.Identity Mat3x3.MatVecMultiplication Mat3x3.MatMatMultiplication Mat3x3.Transpose Mat3x3.Determinant Mat3x3.Inverse Mat3x3.SingularInverse Mat3x3.RotationAxisAngle90 Mat3x3.RotationPreservesNorm Mat3x3.FuzzyEquals Mat3x3.ToString)
