if(EXISTS "/home/runner/work/Gector2/Gector2/build_test/tests/test_smoke[1]_tests.cmake")
  include("/home/runner/work/Gector2/Gector2/build_test/tests/test_smoke[1]_tests.cmake")
else()
  add_test(test_smoke_NOT_BUILT test_smoke_NOT_BUILT)
endif()
