add_test([=[Quaternion.DefaultIsIdentity]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.DefaultIsIdentity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.DefaultIsIdentity]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.IdentityFactory]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.IdentityFactory]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.IdentityFactory]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.FromAxisAngle]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.FromAxisAngle]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.FromAxisAngle]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.IdentityMultiplication]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.IdentityMultiplication]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.IdentityMultiplication]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.Conjugate]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.Conjugate]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.Conjugate]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.QuaternionTimesConjugateIsIdentity]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.QuaternionTimesConjugateIsIdentity]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.QuaternionTimesConjugateIsIdentity]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.Rotate90AboutZ]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.Rotate90AboutZ]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.Rotate90AboutZ]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.RotatePreservesNorm]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.RotatePreservesNorm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.RotatePreservesNorm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.ToMatrixConsistency]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.ToMatrixConsistency]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.ToMatrixConsistency]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.UnitNorm]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.UnitNorm]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.UnitNorm]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.NormalizedOfNonUnit]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.NormalizedOfNonUnit]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.NormalizedOfNonUnit]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.FuzzyEqualsNegation]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.FuzzyEqualsNegation]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.FuzzyEqualsNegation]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Quaternion.ToString]=]  /home/runner/work/Gector2/Gector2/build_test/tests/test_quaternion [==[--gtest_filter=Quaternion.ToString]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Quaternion.ToString]=]  PROPERTIES WORKING_DIRECTORY /home/runner/work/Gector2/Gector2/build_test/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_quaternion_TESTS Quaternion.DefaultIsIdentity Quaternion.IdentityFactory Quaternion.FromAxisAngle Quaternion.IdentityMultiplication Quaternion.Conjugate Quaternion.QuaternionTimesConjugateIsIdentity Quaternion.Rotate90AboutZ Quaternion.RotatePreservesNorm Quaternion.ToMatrixConsistency Quaternion.UnitNorm Quaternion.NormalizedOfNonUnit Quaternion.FuzzyEqualsNegation Quaternion.ToString)
